# Generated by Django 5.2.14 on 2026-05-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zinnia', '0007_alter_entry_options'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='entry',
            new_name='zinnia_entr_slug_a9173b_idx',
            old_name='zinnia_entr_slug_pubdate_idx',
        ),
        migrations.RenameIndex(
            model_name='entry',
            new_name='zinnia_entr_status_7aff0a_idx',
            old_name='zinnia_entr_status_pubdate_idx',
        ),
    ]
