# Fix index names auto-generated by Django 5.x.
#
# This migration is purely cosmetic from PostgreSQL's perspective: the
# index column sets don't change, only the names. We rename whichever
# variant exists in the database, with no-ops for the rest:
#
#   - 'zinnia_entr_*_pubdate_idx': fresh deploys that ran 0003_publication_date
#     against the smartlgt fork, where the indexes were created with
#     explicit name= arguments.
#   - 'zinnia_entry_*_<hash>_idx': legacy deploys whose 0001/0003 were
#     faked or ran against an upstream zinnia that had Meta.indexes
#     without name=, so Django auto-named them.
#
# The state_operations keep Django's autodetector quiet either way.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zinnia', '0007_alter_entry_options'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        # smartlgt-fork explicit-name path
                        "ALTER INDEX IF EXISTS zinnia_entr_slug_pubdate_idx "
                        "RENAME TO zinnia_entr_slug_a9173b_idx;"
                        "ALTER INDEX IF EXISTS zinnia_entr_status_pubdate_idx "
                        "RENAME TO zinnia_entr_status_7aff0a_idx;"
                        # Django-autoname path (legacy faked deploys)
                        "ALTER INDEX IF EXISTS zinnia_entry_slug_publication_date_8de07f28_idx "
                        "RENAME TO zinnia_entr_slug_a9173b_idx;"
                        "ALTER INDEX IF EXISTS zinnia_entry_status_publication_date__b9d97cbc_idx "
                        "RENAME TO zinnia_entr_status_7aff0a_idx;"
                    ),
                    reverse_sql=(
                        "ALTER INDEX IF EXISTS zinnia_entr_slug_a9173b_idx "
                        "RENAME TO zinnia_entr_slug_pubdate_idx;"
                        "ALTER INDEX IF EXISTS zinnia_entr_status_7aff0a_idx "
                        "RENAME TO zinnia_entr_status_pubdate_idx;"
                    ),
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='entry',
                    new_name='zinnia_entr_slug_a9173b_idx',
                    old_name='zinnia_entr_slug_pubdate_idx',
                ),
                migrations.RenameIndex(
                    model_name='entry',
                    new_name='zinnia_entr_status_7aff0a_idx',
                    old_name='zinnia_entr_status_pubdate_idx',
                ),
            ],
        ),
    ]
