# Generated by Django 5.0.9 on 2024-10-17 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zinnia", "0007_alter_entry_options"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="entry",
            new_name="zinnia_entr_status_7aff0a_idx",
            old_fields=(
                "status",
                "publication_date",
                "start_publication",
                "end_publication",
            ),
        ),
        migrations.RenameIndex(
            model_name="entry",
            new_name="zinnia_entr_slug_a9173b_idx",
            old_fields=("slug", "publication_date"),
        ),
    ]